import React, { useState, useEffect, useRef } from "react";
import {
  Send,
  Sparkles,
  Bot,
  User,
  ShieldCheck,
  RotateCcw,
  Building2,
  TrendingUp,
  Coins,
  MapPin,
  HelpCircle,
  Zap,
} from "lucide-react";
import { apiClient } from "../../api/client";
import { useToast } from "../../context/ToastContext";
import { SubsidyOfferCard } from "./cards/SubsidyOfferCard";
import { SchemeDraftCard } from "./cards/SchemeDraftCard";
import { CompanyAssessmentCard } from "./cards/CompanyAssessmentCard";
import { BudgetForecastCard } from "./cards/BudgetForecastCard";

interface Message {
  id: string;
  role: "user" | "assistant" | "system";
  content: string;
  tool_name?: string;
  tool_payload?: any;
  created_at: string;
}

interface UICard {
  id: string;
  card_type:
    | "subsidy_offer"
    | "scheme_draft"
    | "company_assessment"
    | "budget_forecast"
    | "profile_summary"
    | "confirmation_card";
  data: any;
}

interface PendingAction {
  id: string;
  action_type: string;
  payload: any;
  status: string;
  expires_at: string;
}

interface CouncilAgentChatProps {
  onSelectBusiness?: (businessId: string) => void;
  prefillMessage?: string;
}

export const CouncilAgentChat: React.FC<CouncilAgentChatProps> = ({
  onSelectBusiness,
  prefillMessage,
}) => {
  const { showToast } = useToast();
  const [conversationId, setConversationId] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [uiCards, setUiCards] = useState<UICard[]>([]);
  const [pendingAction, setPendingAction] = useState<PendingAction | null>(
    null,
  );
  const [inputText, setInputText] = useState("");
  const [loading, setLoading] = useState(false);
  const [initialising, setInitialising] = useState(true);

  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Quick suggestions
  const SUGGESTIONS = [
    {
      label: "🚲 Assess Chesham Bike Works",
      prompt: "Assess Chesham Community Bike Works wage subsidy proposal",
    },
    {
      label: "📊 Model 10 Youth Cohort",
      prompt:
        "Model 10 youth placements at £4.50 per hour for 16 hrs a week for 24 weeks",
    },
    {
      label: "📍 Deprivation Catchments",
      prompt: "Show high deprivation wards and SME density in Buckinghamshire",
    },
    {
      label: "🏢 Find Eligible Tech SMEs",
      prompt: "Find eligible technology businesses needing wage subsidies",
    },
    {
      label: "💰 Draft £50k Scheme",
      prompt: "Draft a new £50,000 High Street Youth Wage Subsidy Scheme",
    },
  ];

  // Initialize or fetch active council conversation
  useEffect(() => {
    const initConversation = async () => {
      try {
        setInitialising(true);
        const res: any = await apiClient("/conversations", {
          method: "POST",
          body: JSON.stringify({ mode: "council" }),
        });
        setConversationId(res.id);
        setMessages(res.messages || []);
        if (res.pending_actions && res.pending_actions.length > 0) {
          setPendingAction(res.pending_actions[0]);
        }
      } catch (err: any) {
        showToast("Failed to connect to Council AI Orchestrator.", "error");
      } finally {
        setInitialising(false);
      }
    };

    initConversation();
  }, []);

  // Handle prefill message triggered from parent (e.g. Map "Ask AI to Assess")
  useEffect(() => {
    if (prefillMessage && conversationId) {
      sendMessage(prefillMessage);
    }
  }, [prefillMessage, conversationId]);

  // Scroll to bottom on new message
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, uiCards]);

  const sendMessage = async (text?: string) => {
    const content = text || inputText;
    if (!content.trim() || !conversationId) return;

    setInputText("");
    const tempUserMsg: Message = {
      id: `temp-${Date.now()}`,
      role: "user",
      content,
      created_at: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, tempUserMsg]);
    setLoading(true);

    try {
      const res: any = await apiClient(
        `/conversations/${conversationId}/messages`,
        {
          method: "POST",
          body: JSON.stringify({ content }),
        },
      );

      // Handle assistant message
      if (res.message) {
        setMessages((prev) => [...prev, res.message]);
      }

      // Handle UI cards generated by backend tools
      if (res.ui_cards && res.ui_cards.length > 0) {
        setUiCards((prev) => [...prev, ...res.ui_cards]);
      }

      // Handle pending actions
      if (res.pending_actions && res.pending_actions.length > 0) {
        setPendingAction(res.pending_actions[0]);
      }
    } catch (err: any) {
      showToast(err.message || "Failed to communicate with agent.", "error");
    } finally {
      setLoading(false);
    }
  };

  const handleConfirmAction = async (actionId: string) => {
    if (!conversationId) return;
    setLoading(true);
    try {
      const res: any = await apiClient(
        `/conversations/${conversationId}/actions/${actionId}/confirm`,
        {
          method: "POST",
        },
      );
      showToast(res.message || "Action successfully executed.", "success");
      setPendingAction(null);
      // Append confirmation message to chat
      if (res.result) {
        const confirmMsg: Message = {
          id: `conf-${Date.now()}`,
          role: "assistant",
          content: `✅ ${res.message}`,
          created_at: new Date().toISOString(),
        };
        setMessages((prev) => [...prev, confirmMsg]);
      }
    } catch (err: any) {
      showToast(err.message || "Failed to confirm action.", "error");
    } finally {
      setLoading(false);
    }
  };

  const handleCancelAction = async (actionId: string) => {
    if (!conversationId) return;
    try {
      await apiClient(
        `/conversations/${conversationId}/actions/${actionId}/cancel`,
        {
          method: "POST",
        },
      );
      showToast("Action cancelled.", "info");
      setPendingAction(null);
    } catch (err: any) {
      showToast(err.message || "Failed to cancel action.", "error");
    }
  };

  const handlePledgeFromCard = (
    _businessId: string,
    businessName: string,
    recommendedRate: number,
  ) => {
    sendMessage(
      `Confirm wage subsidy pledge for ${businessName} at £${recommendedRate.toFixed(2)}/hr top-up`,
    );
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 border border-slate-800 rounded-3xl overflow-hidden shadow-2xl">
      {/* Agent Header */}
      <div className="px-5 py-3.5 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-emerald-500 to-teal-400 text-slate-950 flex items-center justify-center shadow-md">
            <Bot className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="font-black text-sm text-white">
                Council AI Director
              </h3>
              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[10px] font-mono font-bold bg-emerald-500/15 text-emerald-400 border border-emerald-500/30">
                Live Orchestrator
              </span>
            </div>
            <p className="text-[11px] text-slate-400 font-mono">
              Spatial Wage Gap Analysis, Grant Drafting & Cohort ROI Modeler
            </p>
          </div>
        </div>

        <button
          type="button"
          onClick={() => {
            setMessages([]);
            setUiCards([]);
            sendMessage("Hello! What is my council fund status?");
          }}
          className="p-2 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-400 hover:text-white border border-slate-800 transition-all text-xs flex items-center gap-1 cursor-pointer"
          title="Reset conversation feed"
        >
          <RotateCcw className="w-3.5 h-3.5" />
        </button>
      </div>

      {/* Quick Suggestion Chips */}
      <div className="px-4 py-2 bg-slate-950/80 border-b border-slate-800 overflow-x-auto flex items-center gap-2 scrollbar-none font-mono">
        <span className="text-[10px] uppercase font-bold text-slate-400 tracking-wider shrink-0 flex items-center gap-1">
          <Sparkles className="w-3 h-3 text-emerald-400" /> Prompts:
        </span>
        {SUGGESTIONS.map((s, idx) => (
          <button
            key={idx}
            type="button"
            onClick={() => sendMessage(s.prompt)}
            disabled={loading}
            className="px-2.5 py-1 rounded-full bg-slate-900 border border-slate-800 hover:border-emerald-500/40 hover:bg-slate-850 text-[11px] font-semibold text-slate-300 hover:text-white transition-all shrink-0 cursor-pointer shadow-sm"
          >
            {s.label}
          </button>
        ))}
      </div>

      {/* Messages Scroll View */}
      <div className="flex-1 p-4 overflow-y-auto space-y-4 bg-slate-950">
        {initialising ? (
          <div className="h-full flex flex-col items-center justify-center text-slate-400 space-y-2 py-12 font-mono">
            <div className="w-8 h-8 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin" />
            <span className="text-xs font-semibold">
              Connecting to Council Policy Orchestrator...
            </span>
          </div>
        ) : messages.length === 0 ? (
          <div className="h-full flex flex-col items-center justify-center text-center p-6 space-y-3 my-8">
            <div className="w-12 h-12 rounded-2xl bg-emerald-500/15 border border-emerald-500/30 text-emerald-400 flex items-center justify-center shadow-inner">
              <Bot className="w-6 h-6" />
            </div>
            <div className="space-y-1 max-w-sm">
              <h4 className="font-black text-sm text-white">
                Welcome to your AI Policy & Wage Subsidy Agent
              </h4>
              <p className="text-xs text-slate-400 leading-relaxed">
                I can evaluate local micro/small business wage gaps, model
                multi-youth cohort budgets, and draft grant pledges to co-fund
                living wages.
              </p>
            </div>
          </div>
        ) : (
          messages.map((m) => (
            <div
              key={m.id}
              className={`flex gap-3 ${m.role === "user" ? "justify-end" : "justify-start"}`}
            >
              {m.role !== "user" && (
                <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-emerald-500 to-teal-400 text-slate-950 flex items-center justify-center shrink-0 shadow-sm">
                  <Bot className="w-4 h-4" />
                </div>
              )}

              <div
                className={`max-w-[85%] rounded-2xl p-4 text-xs leading-relaxed ${
                  m.role === "user"
                    ? "bg-emerald-950/80 border border-emerald-500/40 text-emerald-100 rounded-tr-none shadow-md font-medium"
                    : "bg-slate-900 text-slate-200 rounded-tl-none border border-slate-800 shadow-sm"
                }`}
              >
                <div className="whitespace-pre-wrap">{m.content}</div>
              </div>

              {m.role === "user" && (
                <div className="w-8 h-8 rounded-xl bg-slate-800 border border-slate-700 text-emerald-400 flex items-center justify-center shrink-0 shadow-sm">
                  <User className="w-4 h-4" />
                </div>
              )}
            </div>
          ))
        )}

        {/* Render Generated UI Cards */}
        {uiCards.map((card) => (
          <div key={card.id} className="pt-1">
            {card.card_type === "subsidy_offer" && (
              <SubsidyOfferCard
                data={card.data}
                onConfirm={handleConfirmAction}
                onCancel={handleCancelAction}
                onSelectBusiness={onSelectBusiness}
              />
            )}
            {card.card_type === "scheme_draft" && (
              <SchemeDraftCard
                data={card.data}
                onConfirm={handleConfirmAction}
                onCancel={handleCancelAction}
              />
            )}
            {card.card_type === "company_assessment" && (
              <CompanyAssessmentCard
                data={card.data}
                onPledgeClick={handlePledgeFromCard}
                onLocateMap={onSelectBusiness}
              />
            )}
            {card.card_type === "budget_forecast" && (
              <BudgetForecastCard data={card.data} />
            )}
          </div>
        ))}

        {loading && (
          <div className="flex items-center gap-2 text-xs text-slate-400 bg-slate-900 p-3 rounded-2xl border border-slate-800 max-w-[220px] font-mono">
            <div className="w-2 h-2 rounded-full bg-emerald-400 animate-ping" />
            <span className="font-semibold">AI Director is calculating...</span>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input Composer */}
      <div className="p-3.5 bg-slate-950 border-t border-slate-800">
        <form
          onSubmit={(e) => {
            e.preventDefault();
            sendMessage();
          }}
          className="flex items-center gap-2"
        >
          <input
            type="text"
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            placeholder="Ask AI Policy Director (e.g. 'Pledge £4.50/hr to Chesham Bikes' or 'Model 10 youth')..."
            disabled={loading}
            className="flex-1 px-4 py-2.5 bg-slate-900 border border-slate-800 rounded-xl text-xs font-semibold text-white placeholder:text-slate-500 focus:outline-none focus:border-emerald-500 transition-all"
          />

          <button
            type="submit"
            disabled={loading || !inputText.trim()}
            className="p-2.5 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-400 text-slate-950 font-bold hover:from-emerald-400 hover:to-teal-300 shadow-md shadow-emerald-950/40 disabled:opacity-40 transition-all cursor-pointer"
          >
            <Send className="w-4 h-4" />
          </button>
        </form>
      </div>
    </div>
  );
};
