import React, { useState, useEffect } from "react";
import { councilsApi } from "../../api/councils";
import { CouncilAnalytics } from "@springboard/shared-types";
import { LoadingSpinner } from "../../components/common/LoadingSpinner";
import {
  LineChart,
  TrendingUp,
  Coins,
  Users,
  Building2,
  Sparkles,
  PieChart,
  ShieldCheck,
  CheckCircle2,
  Calendar,
  Zap,
} from "lucide-react";

export const CouncilAnalyticsPage: React.FC = () => {
  const [analytics, setAnalytics] = useState<CouncilAnalytics | null>(null);
  const [loading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    const loadAnalytics = async () => {
      try {
        const data = await councilsApi.getAnalytics();
        setAnalytics(data);
      } catch (err) {
        console.error("Failed to load analytics:", err);
      } finally {
        setLoading(false);
      }
    };

    loadAnalytics();
  }, []);

  if (loading || !analytics) {
    return (
      <div className="py-24 flex justify-center bg-slate-950 min-h-[70vh]">
        <LoadingSpinner
          size="lg"
          text="Calculating economic and social mobility impact..."
        />
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 space-y-8 text-slate-100">
      {/* Header */}
      <div>
        <div className="flex items-center gap-2">
          <span className="text-[10px] font-mono font-bold uppercase px-2.5 py-0.5 rounded-md bg-purple-500/15 text-purple-300 border border-purple-500/30 flex items-center gap-1.5">
            <Zap className="w-3 h-3" />
            Impact & Audit Intelligence
          </span>
        </div>
        <h1 className="text-2xl font-black text-white mt-1">
          Social Mobility & Economic Impact Analytics
        </h1>
        <p className="text-xs text-slate-400">
          Measure the local economic return on investment (ROI), youth
          retention, and living wage outcomes generated by council wage
          subsidies.
        </p>
      </div>

      {/* Hero Multiplier Card */}
      <div className="bg-gradient-to-br from-slate-950 via-emerald-950 to-slate-900 text-white rounded-3xl p-6 sm:p-8 shadow-2xl border border-slate-800 flex flex-col md:flex-row md:items-center justify-between gap-6 relative overflow-hidden">
        <div className="space-y-3 max-w-xl relative z-10">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/15 text-emerald-300 text-xs font-mono font-bold border border-emerald-500/30">
            <Sparkles className="w-4 h-4 text-emerald-400" />
            <span>Treasury Green Book Aligned Multiplier</span>
          </div>
          <h2 className="text-2xl sm:text-3xl font-black">
            £{analytics.social_mobility_roi_multiplier.toFixed(1)}x Economic
            Return per £1 Subsidised
          </h2>
          <p className="text-xs sm:text-sm text-slate-300 leading-relaxed">
            Every £1.00 of council wage subsidy unlocks an estimated £3.80 in
            immediate local economic circulation, increased tax receipts,
            reduced benefit claims, and long-term youth human capital
            accumulation.
          </p>
        </div>

        <div className="bg-slate-900/90 rounded-2xl p-6 border border-slate-800 text-center min-w-[200px] shadow-xl relative z-10 font-mono">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
            Youth Retention Rate
          </span>
          <p className="text-4xl font-black text-emerald-400 mt-1">
            {analytics.retention_rate_percentage}%
          </p>
          <p className="text-[11px] text-slate-400 mt-1">
            Staying in work or training
          </p>
        </div>
      </div>

      {/* 4 Metrics Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 font-mono">
        <div className="bg-slate-900/90 rounded-3xl p-5 border border-slate-800 shadow-xl space-y-2">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
            Low-Income Youth Placed
          </span>
          <p className="text-2xl font-black text-white">
            {analytics.total_youth_supported_low_income}
          </p>
          <p className="text-[11px] text-emerald-400 font-bold">
            100% verified pupil-premium catchments
          </p>
        </div>

        <div className="bg-slate-900/90 rounded-3xl p-5 border border-slate-800 shadow-xl space-y-2">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
            Total Hours Subsidised
          </span>
          <p className="text-2xl font-black text-white">
            {analytics.total_hours_subsidised.toLocaleString()}
          </p>
          <p className="text-[11px] text-slate-400">
            Paid at £11.44+ Real Living Wage
          </p>
        </div>

        <div className="bg-slate-900/90 rounded-3xl p-5 border border-slate-800 shadow-xl space-y-2">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
            Average Hourly Top-up
          </span>
          <p className="text-2xl font-black text-emerald-400">
            £{analytics.average_hourly_top_up.toFixed(2)}
          </p>
          <p className="text-[11px] text-slate-400">
            Per hour per young worker
          </p>
        </div>

        <div className="bg-slate-900/90 rounded-3xl p-5 border border-slate-800 shadow-xl space-y-2">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
            Participating Employers
          </span>
          <p className="text-2xl font-black text-white">
            {analytics.participating_businesses_count}
          </p>
          <p className="text-[11px] text-slate-400">Local independent SMEs</p>
        </div>
      </div>

      {/* Sector Breakdown and Monthly Trends */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Sector Allocation Breakdown */}
        <div className="bg-slate-900/90 rounded-3xl p-6 border border-slate-800 shadow-xl space-y-4">
          <h3 className="font-black text-white text-base flex items-center gap-2">
            <PieChart className="w-4 h-4 text-emerald-400" />
            <span>Fund Distribution by Industry Sector</span>
          </h3>
          <div className="space-y-3 font-mono">
            {analytics.sector_breakdown.map((sec, idx) => (
              <div key={idx} className="space-y-1.5">
                <div className="flex items-center justify-between text-xs">
                  <span className="font-bold text-white font-sans">
                    {sec.sector}
                  </span>
                  <span className="font-bold text-emerald-400">
                    £{sec.subsidies_allocated.toLocaleString()} (
                    {sec.business_count} SME{sec.business_count > 1 ? "s" : ""})
                  </span>
                </div>
                <div className="w-full bg-slate-950 rounded-full h-2 overflow-hidden border border-slate-800">
                  <div
                    className="bg-emerald-500 h-full rounded-full"
                    style={{
                      width: `${Math.min(100, (sec.subsidies_allocated / (analytics.total_budget_spent || 1)) * 100)}%`,
                    }}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Monthly Placements Trend */}
        <div className="bg-slate-900/90 rounded-3xl p-6 border border-slate-800 shadow-xl space-y-4">
          <h3 className="font-black text-white text-base flex items-center gap-2">
            <Calendar className="w-4 h-4 text-sky-400" />
            <span>Monthly Youth Placements & Fund Outflow</span>
          </h3>
          <div className="space-y-3 font-mono">
            {analytics.monthly_trends.map((trend, idx) => (
              <div
                key={idx}
                className="flex items-center justify-between p-3.5 rounded-2xl bg-slate-950 border border-slate-800 text-xs"
              >
                <div>
                  <span className="font-bold text-white block">
                    {trend.month}
                  </span>
                  <span className="text-[11px] text-sky-400 font-bold">
                    {trend.youth_placed} youth placed
                  </span>
                </div>
                <div className="text-right">
                  <span className="font-black text-white block">
                    £{trend.funds_disbursed.toLocaleString()}
                  </span>
                  <span className="text-[10px] text-slate-400 uppercase font-bold">
                    Disbursed
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};
